// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBub0xlpbD749dElnx6helhMDpStqI0WNA',
    appId: '1:577992143910:web:04cdc1e79964439bc1a2e7',
    messagingSenderId: '577992143910',
    projectId: 'croshez-1da29',
    authDomain: 'croshez-1da29.firebaseapp.com',
    storageBucket: 'croshez-1da29.appspot.com',
    measurementId: 'G-S8BK4FGETK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LwrTwsg851bLs-BdufjGgyjCu6YUY1Y',
    appId: '1:577992143910:android:8d2c7fa14a53aacac1a2e7',
    messagingSenderId: '577992143910',
    projectId: 'croshez-1da29',
    storageBucket: 'croshez-1da29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-3gP2seQD6m3-BhRttz98jx2xCqeihw',
    appId: '1:577992143910:ios:28b38b08381a1bf3c1a2e7',
    messagingSenderId: '577992143910',
    projectId: 'croshez-1da29',
    storageBucket: 'croshez-1da29.appspot.com',
    iosClientId: '577992143910-vn1ksi0i66hc00qr4lctfamg1a5023v4.apps.googleusercontent.com',
    iosBundleId: 'com.weoveri.croshez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-3gP2seQD6m3-BhRttz98jx2xCqeihw',
    appId: '1:577992143910:ios:28b38b08381a1bf3c1a2e7',
    messagingSenderId: '577992143910',
    projectId: 'croshez-1da29',
    storageBucket: 'croshez-1da29.appspot.com',
    iosClientId: '577992143910-vn1ksi0i66hc00qr4lctfamg1a5023v4.apps.googleusercontent.com',
    iosBundleId: 'com.weoveri.croshez',
  );
}
