# This file contains the fastlane.tools configuration

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(
      task: "assemble",
      flavor: "prod",
      build_type: "Release"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Ensure the Flutter environment is available
    sh "flutter pub get"
    sh "flutter build appbundle"
    # Validate the Play Store JSON key
    # validate_play_store_json_key(
    #   json_key: "#{ENV['GITHUB_WORKSPACE']}/android/my_secret.json"
    # )
    # Upload the app bundle to Google Play
    upload_to_play_store(
      track: 'internal',
      # release_status: 'draft',
      skip_upload_apk: true,
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      # validate_only: true,
      aab: "#{ENV['GITHUB_WORKSPACE']}/build/app/outputs/bundle/release/app-release.aab", # Adjusted path
      # json_key: "#{ENV['GITHUB_WORKSPACE']}/android/my_secret.json",
    )
  end
end
