name: Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # - name: Create Service Account JSON File
      #   run: |
      #     cd android && echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" > Gplay.json
      #   shell: bash

      - name: Decode JSON secret and write to file
        run: echo "$GPLAY_SERVICE_ACCOUNT_KEY_JSON" > my_secret.json
        env:
          MY_JSON_SECRET: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      # - name: Install Dependencies
      #   run: bundle install

      - name: Get Fastlane Version
        run: |
          fastlane run get_version_number
      
      # - name: Build & deploy Android release
      #   run: |
      #     # cd android && bundle exec fastlane android deploy
      #     cd android && fastlane action upload_to_play_store
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}
      #     KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
      #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #     ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: assets
      #     path: |
      #       ${{ github.workspace }}/app/build/outputs/bundle/app-release.aab
