name: Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'

      - name: Decode JSON secret and write to file
        run: echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" > android/my_secret.json

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter APK
        run: flutter build apk --release

      - name: Fastlane Deploy
        run: |
          cd android && fastlane android deploy --verbose
