name: Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'

      - name: Decode JSON secret and write to file
        run: echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" > android/my_secret.json
      
      - name: Set proper permissions for the JSON file
        run: chmod 644 android/my_secret.json

      - name: Print JSON Key File Content
        run: cat android/my_secret.json

      - name: Update packages
        run: flutter pub outdated

      - name: Clean build
        run: flutter clean

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Print JSON Key File Content
        run: cat android/my_secret.json

      - name: Fastlane Deploy
        run: |
          cd android && fastlane android deploy --verbose
