name: Android Build & Deploy

on:
  push:
    branches:
      - main

env:
 PROPERTIES_PATH: "android/key.properties"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'

      - name: Decode jks file
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/key.jks

      - name: Create key.properties file
        run: |
          echo storeFile=android/app/key.jks > ${{env.PROPERTIES_PATH}} 
          echo abcd > ${{env.PROPERTIES_PATH}} 
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo abcd > ${{env.PROPERTIES_PATH}} 

      - name: Print Key File Content
        run: cat android/key.properties

      # - name: Print Key File Content
      #   run: cat android/app/key.jks

      # - name: Build apk
      #   run: | 
      #     flutter clean && flutter pub get && flutter build apk

      # - name: Decode JSON secret and write to file
      #   run: echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" | base64 -d > android/my_secret.json
      
      # - name: Set proper permissions for the JSON file
      #   run: chmod 644 android/my_secret.json

      # - name: Print JSON Key File Content
      #   run: cat android/my_secret.json

      # - name: Update packages
      #   run: flutter pub outdated

      # - name: Clean build
      #   run: flutter clean

      # - name: Install Flutter Dependencies
      #   run: flutter pub get

      # - name: Fastlane Deploy
      #   run: |
      #     cd android && fastlane android deploy --verbose
